<?php
/**
 * Zkilleman_Navigator
 *
 * Copyright (C) 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Navigator.
 *
 * Zkilleman_Navigator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Navigator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Zkilleman_Navigator.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP Version 5.1
 *
 * @category  Zkilleman
 * @package   Zkilleman_Navigator
 * @author    Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 * @link      https://github.com/henkelund/magento-zkilleman-navigator
 */
?>
<?php 
    //TODO: To much logic here, please refactor
    $_node = $this->getNode();
    $_displayUseDefault = ($_node->getId() && $_node->getStoreId());
    $_attribute = $_node->getResource()->getAttribute('visibility');
    $_usedDefault = null;
    $attributeCode = $_attribute->getAttributeCode();
    $defaultValue = $_node->getAttributeDefaultValue($attributeCode);
    if (!$_node->getExistsStoreValueFlag($attributeCode)) {
        $_usedDefault = true;
    } else if ($_node->getData('visibility') == $defaultValue &&
               $_node->getStoreId() != 0) {
        $_usedDefault = false;
    }
    if ($_usedDefault === null && $defaultValue === false && !$_attribute->getIsRequired() && $_node->getData('visibility')) {
        $_usedDefault = false;
    }
    if ($_usedDefault === null) {
        $_usedDefault = ($defaultValue === false);
    }
?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">
        <?php echo Mage::helper('navigator')->__('Visibility Conditions'); ?>
    </h4>
    <div class="form-buttons"></div>
</div>
<div class="fieldset fieldset-wide" id="navigator_node_visibility_fieldset">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
        <tr>
            <td class="label"><?php echo Mage::helper('navigator')->__('Node is visible...'); ?></td>
            <td class="conditions" style="padding: 5px;">
                <div id="visibilityFormContainer" class="rule-tree">
                    <?php echo $this->getVisibilityModel()->getEditBlock()->toHtml(); ?>
                </div>
            </td>
            <td class="scope-label"><span class="nobr">[STORE VIEW]</span>
            </td>
            <?php if ($_displayUseDefault): ?>
            <td class="value use-default" style="width: 185px !important;">
                <input type="checkbox" value="visibility"<?php if ($_usedDefault): ?> checked="checked"<?php endif; ?> id="navigator_node_visibility_default" name="use_default[]">
                <label class="normal" for="navigator_node_visibility_default">Use Default Value</label>
            </td>
            <?php endif; ?>
        </tr>
        </table>
    </div>
</div>
<script type="text/javascript">

    var visibilityForm = new VarienRulesForm(
        'visibilityFormContainer',
        '<?php echo $this->getUrl('*/adminhtml_node/newVisibility'); ?>'
    );

    <?php if ($_displayUseDefault): ?>
    function toggleVisibilityForm()
    {
        if ($('navigator_node_visibility_default').checked) {
            $('visibilityFormContainer').hide();
        }
        else {
            $('visibilityFormContainer').show();
        }
    }

    Event.observe('navigator_node_visibility_default', 'change', toggleVisibilityForm);
    toggleVisibilityForm();
    <?php endif; ?>

</script>

