<?php
/**
 * Zkilleman_Navigator
 *
 * Copyright (C) 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Navigator.
 *
 * Zkilleman_Navigator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Navigator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Zkilleman_Navigator.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP Version 5.1
 *
 * @category  Zkilleman
 * @package   Zkilleman_Navigator
 * @author    Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 * @link      https://github.com/henkelund/magento-zkilleman-navigator
 */
?>
<?php
    $_model = $this->getVisibilityModel();
    $_id = $_model->getCondId();
?>
<input type="hidden" class="hidden" value="group" name="rule[conditions][<?php echo $_id; ?>][type]" id="conditions__<?php echo $_id; ?>__type">
If
<span class="rule-param">
    <a class="label" href="javascript:void(0);"><?php echo $_model->getSelectedAggregatorLabel(); ?></a>
    <span class="element">
        <select id="conditions__<?php echo $_id; ?>__aggregator" class="element-value-changer" name="rule[conditions][<?php echo $_id; ?>][aggregator]">
            <?php foreach($_model->getAggregatorOptions() as $value => $label): ?>
            <?php $selected = ($value == $_model->getAggregator()); ?>
            <option value="<?php echo $value; ?>"<?php if($selected): ?> selected="selected"<?php endif; ?>><?php echo $label; ?></option>
            <?php endforeach; ?>
        </select>
    </span>
</span>
of these conditions are
<span class="rule-param">
    <a class="label" href="javascript:void(0);"><?php echo $_model->getSelectedValueLabel(); ?></a>
    <span class="element">
        <select id="conditions__<?php echo $_id; ?>__value" class="element-value-changer" name="rule[conditions][<?php echo $_id; ?>][value]">
            <?php foreach($_model->getValueOptions() as $value => $label): ?>
            <?php $selected = ($value == $_model->getValue()); ?>
            <option value="<?php echo $value; ?>"<?php if($selected): ?> selected="selected"<?php endif; ?>><?php echo $label; ?></option>
            <?php endforeach; ?>
        </select>
    </span>
</span>
:
<?php if(((string)$_model->getCondId()) != '1'): ?>
<span class="rule-param" id="">
    <a title="Remove" class="rule-param-remove" href="javascript:void(0)">
        <img class="v-middle" src="<?php echo $this->getSkinUrl('images'); ?>/rule_component_remove.gif">
    </a>
</span>
<?php endif; ?>
<ul id="conditions__<?php echo $_id; ?>__children" class="condition-list">
    <?php $children = $_model->getChildren(); ?>
    <?php foreach($children as $child): ?>
    <li>
        <?php echo $child->getEditBlock()->toHtml(); ?>
    </li>
    <?php endforeach; ?>
    <li>
        <span class="rule-param rule-param-new-child">
            <a class="label" href="javascript:void(0);">
                <img class="v-middle" src="<?php echo $this->getSkinUrl('images'); ?>/rule_component_add.gif" />
            </a>
            <span class="element">
                <select id="conditions__<?php echo $_id; ?>__new_child" class="element-value-changer">
                    <option value="">
                        <?php echo Mage::helper('navigator')->__('Choose an option...'); ?>
                    </option>
                    <?php foreach($_model->getAvailableConditions() as $value => $label): ?>
                    <option value="<?php echo $value; ?>"><?php echo $label; ?></option>
                    <?php endforeach; ?>
                </select>
            </span>
        </span>
    </li>
</ul>