<?php
/**
 * Zkilleman_Navigator
 *
 * Copyright (C) 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Navigator.
 *
 * Zkilleman_Navigator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Navigator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Zkilleman_Navigator.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP Version 5.1
 *
 * @category  Zkilleman
 * @package   Zkilleman_Navigator
 * @author    Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 * @link      https://github.com/henkelund/magento-zkilleman-navigator
 */
?>
<?php
    $_model = $this->getVisibilityModel();
    $_id = $_model->getCondId();
?>
<input type="hidden" class="hidden" value="<?php echo $_model->getCode(); ?>" name="rule[conditions][<?php echo $_id; ?>][type]" id="conditions__<?php echo $_id; ?>__type">
<?php ob_start(); ?>
<span class="rule-param">
    <a class="label" href="javascript:void(0)"><?php echo $_model->getSelectedValueLabel(); ?></a>
    <span class="element">
        <select class="element-value-changer select" name="rule[conditions][<?php echo $_id; ?>][value]" id="conditions__<?php echo $_id; ?>__value">
            <?php foreach($_model->getSelectOptions() as $value => $label): ?>
            <?php $selected = ($value == $_model->getValue()); ?>
            <option<?php if($selected): ?> selected="selected"<?php endif; ?> value="<?php echo $value; ?>"><?php echo $label; ?></option>
            <?php endforeach; ?>
        </select>
    </span>
</span>
<?php $selectHtml = ob_get_clean(); ?>
<?php echo sprintf($_model->getConditionText(), $selectHtml); ?>
:
<span class="rule-param">
    <a title="Remove" class="rule-param-remove" href="javascript:void(0)">
        <img class="v-middle" src="<?php echo $this->getSkinUrl('images'); ?>/rule_component_remove.gif">
    </a>
</span>