<?php
/**
 * Zkilleman_Navigator
 *
 * Copyright (C) 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 *
 * This file is part of Zkilleman_Navigator.
 *
 * Zkilleman_Navigator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zkilleman_Navigator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Zkilleman_Navigator.  If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP Version 5.1
 *
 * @category  Zkilleman
 * @package   Zkilleman_Navigator
 * @author    Henrik Hedelund <henke.hedelund@gmail.com>
 * @copyright 2011 Henrik Hedelund (henke.hedelund@gmail.com)
 * @license   http://www.gnu.org/licenses/lgpl.html GNU LGPL
 * @link      https://github.com/henkelund/magento-zkilleman-navigator
 */
?>
<div class="content-header">
        <h3 class="icon-head">Node</h3>
        <p class="content-buttons form-buttons">
            <?php /*echo $this->getResetButtonHtml()*/ ?>
            <?php if($this->getNodeId()): ?>
                    <?php echo $this->getChildHtml('delete_button'); ?>
            <?php endif; ?>
            <?php echo $this->getAdditionalButtonsHtml(); ?>
            <?php echo $this->getChildHtml('save_button'); ?>
        </p>
</div>
<?php /* for ajax save..
<iframe name="iframeSave" style="display:none; width:100%;" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>
*/ ?>
<form <?php /* target="iframeSave" */ ?> id="node_edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post">
    <div class="entry-edit">
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
        <?php echo $this->getFormHtml(); ?>
        <?php echo $this->getChildHtml('visibility_fieldset'); ?>
    </div>
</form>
<script type="text/javascript">

    $('navigator_node_content_type').observe('change', function() {

        var type = this.options[this.selectedIndex].value;

        new Ajax.Request('<?php echo $this->getUrl('*/*/contentFieldset'); ?>', {
            parameters : {
                store: tree.storeId,
                id: <?php echo (int)$this->getNodeId(); ?>,
                content_type: type
            },
            method     : 'post',
            onComplete : function(transport) {
                $('<?php echo $this->getContentContainerId(); ?>')
                    .update(transport.responseText);
            }
        });
    });

    nodeForm = new varienForm('node_edit_form');

    nodeForm.submit= function (url) {
        this.errorSections = $H({});
        this.canShowError = true;
        this.submitUrl = url;
        if (this.validator && this.validator.validate()) {
            if(this.validationUrl){
                this._validate();
            }
            else{
                if (this.isSubmitted) {
                    return false;
                }
                this.isSubmitted = true;
                this._submit();
            }
            //displayLoadingMask();
            return true;
        }
        return false;
    };

    function nodeSubmit(url, useAjax) {
        nodeForm.submit(url);
    }

</script>
